/*
Generated by AI with the following prompts:
https://chatgpt.com/share/689411bb-7150-8012-bd4e-b11dbb756027

Script for this build file begins in response to prompt beginning with "You said I could hardcode ..."
Prompts and script edits authored by Grant Fink.

* Each time we add a new URL match pattern, we have to add it to the manifest TWICE.
* One time for a new content_scripts entry, another time for the generic script's exclude_matches.
* That's because a specialized site script should run on the page, but the generic script should not.
* Additionally, we need to create the script file itself.
* This build automates the process so we only have to add the URL once - in the dedicated script file, from where it is exported.
* We don't even open the manifest to add URL matches.
*/

// manifest.json represented as an object
const manifest = {
  name: "Reading Time",
  description: "Estimates the time it takes to read an article.",
  version: "1.0",
  manifest_version: 3,
  action: {
    default_popup: "hello.html",
    default_icon: "clock.png"
  },
  icons: {
    16: "clock.png",
    48: "clock.png",
    128: "clock.png"
  },
  permissions: ["scripting"]
};
// from here on out, we're constructing the content_scripts array

import { readdir, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath, pathToFileURL } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const scriptsDir = path.join(__dirname, "scripts");

const siteScripts = []; // scripts 
const excludePatterns = [];

const filenames = await readdir(scriptsDir);

for (const filename of filenames) {
  // if (file === "generic.js") continue;

  console.log(filename, typeof(filename));
  const modulePath = pathToFileURL(path.join(scriptsDir, file)).href;
  // console.log(modulePath);
  // const { matches } = await import(modulePath);
  continue;
  if (!matches || !Array.isArray(matches)) continue;

  siteScripts.push({
    matches,
    js: [`scripts/${file}`],
    run_at: "document_end"
  });

  excludePatterns.push(...matches);
}

// Build content_scripts array
const contentScripts = [
  ...siteScripts,
  {
    matches: ["<all_urls>"],
    exclude_matches: excludePatterns,
    js: ["scripts/generic.js"],
    // type: "module"
    // this type field does not exist in manifest v3 -Grant
  }
];

// // append it to the manifest
// manifest.content_scripts = contentScripts;

// await writeFile("manifest.json", JSON.stringify(template, null, 2));

// // Write exclusion list to utils/matchList.js for generic.js to import
// const matchExport = `export const excludedMatches = ${JSON.stringify(excludePatterns, null, 2)};\n`;
// await writeFile("matchList.js", matchExport);

console.log("✅ Build complete.");